name: eeg_clean
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - comm=0.2.3
  - debugpy=1.8.20
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.4
  - ipykernel=7.2.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.1
  - packaging=25.0
  - parso=0.8.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=26.0.1
  - platformdirs=4.9.2
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.10.2
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.6.0
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - matplotlib==3.10.8
      - mne==1.11.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - pandas==2.3.3
      - pillow==12.0.0
      - pooch==1.9.0
      - pyparsing==3.3.2
      - pytz==2025.2
      - requests==2.32.5
      - scipy==1.15.3
      - sympy==1.14.0
      - torch==2.10.0+cpu
      - torchaudio==2.10.0+cpu
      - torchvision==0.25.0+cpu
      - tqdm==4.67.3
      - tzdata==2025.3
      - urllib3==2.6.3
prefix: /home/salvatore/miniconda3/envs/eeg_clean
